version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: scrapper
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    networks:
       - backend
       
    

  liquibase-migrations:
   image: liquibase/liquibase:4.18
   depends_on:
       - postgresql
   command:
       - --hub-mode=off
       - --changelog-file=master.xml
       - --driver=org.postgresql.Driver
       - --url=jdbc:postgresql://postgresql:5432/scrapper
       - --username=postgres
       - --password=postgres
       - update
   volumes:
       - ./migrations:/liquibase/changelog
   networks:
       - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - backend
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - backend
    ports:
      - '3000:3000'


volumes:
  pgdata:
  prometheus:
  grafana:
  rabbitmq:
networks:
  backend: