version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: scrapper
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    networks:
       - backend
       
    

  liquibase-migrations:
   image: liquibase/liquibase:4.18
   depends_on:
       - postgresql
   command:
       - --hub-mode=off
       - --changelog-file=master.xml
       - --driver=org.postgresql.Driver
       - --url=jdbc:postgresql://postgresql:5432/scrapper
       - --username=postgres
       - --password=postgres
       - update
   volumes:
       - ./migrations:/liquibase/changelog
   networks:
       - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
volumes:
  pgdata:
  rabbitmq:
networks:
  backend: