name: bot
on: 
  push:
    branches: ["main","hw9"]
  pull_request:
    branches: ["main","hw9"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -a
  
      - name: Setup java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Check java version
        run: java --version
